name: autofix.ci
on: { push: {}, pull_request: {} }
permissions: { contents: read }
jobs:
  autofix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@fbc6f3992d24b796d5a048ff273f7fcc4a7b6c09 # v5.1.0
      - run: npm i -fg corepack && corepack enable
      - uses: actions/setup-node@a0853c24544627f65ddf259abe73b1d18a591444 # v5.0.0
        with: { node-version: lts/*, cache: pnpm }
      - run: pnpm install
      - run: pnpm fmt
      - uses: autofix-ci/action@635ffb0c9798bd160680f18fd73371e355b85f27 # v1.3.2
        with: { commit-message: "chore: apply automated updates" }
